config/routes.rb
Rails.application.routes.draw do
  
  resources :genres
  resource :session

  resources :users
  # resources :reviews
  root "movies#index"
  resources :movies do
    resources :reviews
    resources :favorites
  end

  root "users#index"
  get "signup" => "new"

end

app/models/movie.rb
class Movie < ApplicationRecord

  validates :title, :released_on, :duration, presence: true
  validates :description, length: { minimum: 25 }
  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
  validates :image_file_name, allow_blank: true, format: {
  with:    /\w+\.(gif|jpg|png)\z/i,
  message: "must reference a GIF, JPG, or PNG image"
  }
  RATINGS = %w(G PG PG-13 R NC-17)
  validates :rating, inclusion: { in: RATINGS }
  has_many :reviews
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user 
  has_many :characterizations, dependent: :destroy
  has_many :genres, through: :characterizations

  def self.released
    where("released_on <= ?", Time.now).order("released_on desc")
  end

  def self.hits
    where('total_gross >= 300000000').order(total_gross: :desc)
  end

  def self.flops
    where('total_gross < 50000000').order(total_gross: :asc)
  end

  def self.recently_added
    order('created_at desc').limit(3)
  end

  def flop?
    total_gross.blank? || total_gross < 50000000
  end

  def average_stars
    reviews.average(:stars)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :require_signin, excpet: [:index, :show]
  before_action :require_signin, excpet: [:index, :show]


  def index
    @movies = Movie.released
  end

  def show
    @movie = Movie.find(params[:id])
    @fans = @movie.fans

    if current_user
      @current_favorite = current_user.favorites.find_by(movie_id: @movie.id)
    end

    @genres = @movie.genres
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update()
      redirect_to @movie, notice:  "Movie successfully updated!"
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new()
    if @movie.save
      redirect_to @movie, notice: "Movie successfully created!"
    else
      render :new
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_url, alert: "Movie successfully deleted!"
  end

  def require_admin
    unless current_user_admin?
      redirect_to root_url, alert: "Unauthorized access!"
    end
  end

  def current_user_admin?
    current_user && current_user?
  end

  helper_method :current_user_admin?
private

  def movie_params
    params.require(:movie)
      .permit(:title, :description, :rating, :released_on, :total_gross, :cast, :director, :duration, :image_file_name, genre_ids: [])
  end
end

app/controllers/movies_controller_spec.rb
require 'rails_helper'

describe MoviesController do

  before do
    @movie = Movie.create!(movie_attributes)
  end

  context "when not signed in as an  user" do

    before do
      non_ = User.create!(user_attributes(: false))
      session[:user_id] = non_.id
    end

    it "cannot access new" do
      get :new

      expect(response).to redirect_to(root_url)
    end

    it "cannot access create" do
      post :create

      expect(response).to redirect_to(root_url)
    end

    it "cannot access edit" do
      get :edit, params: { id: @movie }

      expect(response).to redirect_to(root_url)
    end

    it "cannot access update" do
      patch :update, params: { id: @movie }

      expect(response).to redirect_to(root_url)
    end

    it "cannot access destroy" do
      delete :destroy, params: { id: @movie }

      expect(response).to redirect_to(root_url)
    end

  end

end

app/helpers/movies_helper.rb
module MoviesHelper
  def format_total_gross(movie)
    if movie.flop?
      content_tag(:strong, 'Flop!')
    else
      number_to_currency(movie.total_gross)
    end
  end

  def image_for(movie)
    if movie.image_file_name.blank?
      image_tag('placeholder.png')
    else
      image_tag(movie.image_file_name)
    end
  end

  def format_average_stars(movie)
    if movie.average_stars.nil?
      content_tag(:strong, 'No reviews')
    else
      pluralize(number_with_precision(movie.average_stars, precision: 1), 'star')
    end
  end
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <%= render "shared/errors", object: @movie %>
  <%= @movie.errors.full_messages.to_sentence %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :description %>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </li>
      <li class="required">
        <%= f.label :rating %>
        <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
        <%= f.text_field :rating, size: 4 %>
      </li>
      <li class="required">
        <%= f.label :released_on %>
        <%= f.date_select :released_on %>
      </li>
      <li class="required">
        <%= f.label :total_gross %>
        <%= f.number_field :total_gross %>
      </li>
      <li class="required">
        <%= f.label :duration %>
        <%= f.text_field :duration, size: 10 %>
      </li>
      <li class="required">
        <%= f.label :image_file_name %>
        <%= f.text_field :image_file_name %>
      </li>
      <li>
        <%= f.label :cast %>
        <%= f.text_field :cast %>
      </li>
      <li>
        <%= f.label :director %>
        <%= f.text_field :director %>
      </li>
      <li>
        <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) %>
      </li>
    </ol>
    <p>
      <%=  %>
      <%= link_to "Cancel", movies_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/movies/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @movie.title %></h1>
</header>

<%= render 'form' %>

app/views/movies/index.html.erb
<ul id="movies">
  <% @movies.each do |movie| %>
    <li>
      <article class="movie">
        <header>
          <%= image_for(movie) %>
          <h2><%= link_to movie.title, movie %> (<%= movie.released_on.year %>)</h2>
          <h3><%= movie.cast %></h3>
        </header>
        <p>
          <%= truncate(movie.description, length: 150, separator: ' ') %>
        </p>
        <table>
          <tr>
            <th>Rating</th>
            <td><%= movie.rating %></td>
          </tr>
          <tr>
            <th>Duration</th>
            <td><%= movie.duration %></td>
          </tr>
          <tr>
            <th>Total Gross</th>
            <td><%= format_total_gross(movie) %></td>
          </tr>
        </table>
        <footer>
        </footer>
      </article>
    </li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<header id="content-header">
  <h1>Create a New Movie</h1>
</header>

<%= render 'form' %>

app/views/movies/show.html.erb
<article id="movie" class="movie">
  <header>
    <%= image_for(@movie) %>
    <h1><%= @movie.title %></h1>
    <h2>Released: <%= @movie.released_on %></h2>
    <%= link_to pluralize(@movie.reviews.size, "review"), 
            movie_reviews_path(@movie) %>
  
  </header>

  <p>
    <%= @movie.description %>
  </p>

  <h3>Genres</h3>
  <ul>
    <% @genres.each do |genre| %>
      <li><%= genre.name %></li>
    <% end %>
  </ul>
  
  <h3 class="no-rule">
    <%= @movie.rating %> &bull; <%= @movie.duration %> 
  </h3>
  <p>
    <%= pluralize(@fans.size, 'fan') %>
  </p>
  <% if current_user %>
    <% if @current_favorite %>
      <%= button_to "Unfave", '#' %>
    <% else %>
      <%= button_to "Fave", movie_favorites_path(@movie) %>
      <%= button_to "Unfave", movie_favorite_path(@movie, @current_favorite), method: :delete %>
    <% end %>
  <% end %>
  <% if @fans.any? %>
  <h3>Fans</h3>
  <ul>
    <% @fans.each do |user| %>
      <li>
        <%= link_to user.name, user %>
      </li>
    <% end %>
  </ul>
<% end %>
  
  <h3>Cast</h3>
  <p>
    <%= @movie.cast %>
  </p>
  
  <h3>Director</h3>
  <p>
    <%= @movie.director %>
  </p>
  
  <h3>Total Gross</h3>
  <p>
    <%= format_total_gross(@movie) %>
  </p>

  <h3>Average Review</h3>
  <p>
    <%= format_average_stars(@movie) %>
  </p>
  
  <footer>
    <nav>
    <% if current_user_admin? %>
      <%= link_to 'Edit', edit_movie_path(@movie), class: 'button' %>
      <%= link_to 'Delete', @movie, 
                  class: 'button',
                  method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
      <%= link_to "Write Review", new_movie_review_path(@movie),
             class: 'button ok review' %>
    </nav>
  </footer>
</article>