config/routes.rb
Rails.application.routes.draw do
  
  resources :genres
  resource :session

  resources :users
  # resources :reviews
  root "movies#index"
  resources :movies do
    resources :reviews
    resources :favorites
  end

  root "users#index"
  get "signup" => "new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/characterization.rb
class Characterization < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :characterizations, dependent: :destroy
    has_many :movies, through: :characterizations
end

app/models/movie.rb
class Movie < ApplicationRecord

  validates :title, :released_on, :duration, presence: true
  validates :description, length: { minimum: 25 }
  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
  validates :image_file_name, allow_blank: true, format: {
  with:    /\w+\.(gif|jpg|png)\z/i,
  message: "must reference a GIF, JPG, or PNG image"
  }
  RATINGS = %w(G PG PG-13 R NC-17)
  validates :rating, inclusion: { in: RATINGS }
  has_many :reviews
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user 
  has_many :characterizations, dependent: :destroy
  has_many :genres, through: :characterizations

  def self.released
    where("released_on <= ?", Time.now).order("released_on desc")
  end

  def self.hits
    where('total_gross >= 300000000').order(total_gross: :desc)
  end

  def self.flops
    where('total_gross < 50000000').order(total_gross: :asc)
  end

  def self.recently_added
    order('created_at desc').limit(3)
  end

  def flop?
    total_gross.blank? || total_gross < 50000000
  end

  def average_stars
    reviews.average(:stars)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  
  validates :comment, length: { minimum: 4 }

  STARS = [1, 2, 3, 4, 5]

  validates :stars, inclusion: {
    in: STARS,
    message: "must be between 1 and 5"
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_secure_password
  has_many :favorites, dependent: :destroy
  has_many :favorite_movies, through: :favorites, source: :movie

  validates :name, presence: true
  validates :email, presence: true,
                    format: /\A\S+@\S+\z/,
                    uniqueness: { case_sensitive: false }
  

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :require_signin
    before_action :set_movie

    def new
    end

    def create
        @movie = Movie.find(params[:movie_id])
        @movie.favorites.create!(user: current_user)
      
        redirect_to @movie, notice: "Thanks for fav'ing!"
    end

    def destroy
        @movie = Movie.find(params[:movie_id])
        favorite = current_user.favorites.find(params[:id])
        favorite.destroy
        redirect_to @movie, notice: "Sorry you unfaved it!"
    end
end

private

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :require_signin, excpet: [:index, :show]
  before_action :require_signin, excpet: [:index, :show]


  def index
    @movies = Movie.released
  end

  def show
    @movie = Movie.find(params[:id])
    @fans = @movie.fans

    if current_user
      @current_favorite = current_user.favorites.find_by(movie_id: @movie.id)
    end

    @genres = @movie.genres
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update()
      redirect_to @movie, notice:  "Movie successfully updated!"
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new()
    if @movie.save
      redirect_to @movie, notice: "Movie successfully created!"
    else
      render :new
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_url, alert: "Movie successfully deleted!"
  end

  def require_admin
    unless current_user_admin?
      redirect_to root_url, alert: "Unauthorized access!"
    end
  end

  def current_user_admin?
    current_user && current_user?
  end

  helper_method :current_user_admin?
private

  def movie_params
    params.require(:movie)
      .permit(:title, :description, :rating, :released_on, :total_gross, :cast, :director, :duration, :image_file_name, genre_ids: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :require_signin
    before_action :set_movie

    def index
        @reviews = @movie.reviews
    end
    
    def new 
        @reviews = @movie.reviews.new
    end

    
        @reviews = @movie.reviews.new(review_params)
        @review.user = current_user
        if @reviews.save
            redirect_to movie_reviews_path(@movie),
                            notice: "Thanks for your review!"
        else
            render :new
        end
    end

    def set_movie
        @movie = Movie.find(params[:movie_id])
    end

private
    def review_params
        params.require(:review)
            .permit( :stars, :comment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    
        if user = User.authenticate(params[:email], params[:password])
            session[:user_id] = user.id 
            flash[:notice] = "Welcome back, #{user.name}!"
            redirect_to(session[:intended_url] || user)
            session[:intended_url] = nil
        else
            flash.now[:alert] = "Invalid email/password combination!"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url, notice: "You're now signed out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

    def index
        @user = User.all
    end

    def show
        @user = User.find(params[:id])
        @reviews = @user.reviews
        @favorite_movie = @user.favorite_movies
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          redirect_to @user, notice: "Thanks for signing up!"
        else
          render :new
        end
      end
      
      private
      
      def user_params
        params.require(:user).
          permit(:name, :email, :password, :password_confirmation)
      end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to @user, notice: "Account successfully updated!"
        else
          render :edit
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        session[:user_id] = nil
        redirect_to root_url, aler: "Account successfully deleted!"
    end
    def require_correct_user
      @user = User.find(params[:id])
        redirect_to root_url unless current_user?(@user)
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper

  

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def format_total_gross(movie)
    if movie.flop?
      content_tag(:strong, 'Flop!')
    else
      number_to_currency(movie.total_gross)
    end
  end

  def image_for(movie)
    if movie.image_file_name.blank?
      image_tag('placeholder.png')
    else
      image_tag(movie.image_file_name)
    end
  end

  def format_average_stars(movie)
    if movie.average_stars.nil?
      content_tag(:strong, 'No reviews')
    else
      pluralize(number_with_precision(movie.average_stars, precision: 1), 'star')
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2016
    <%= link_to 'The Pragmatic Studio', 'http://pragmaticstudio.com' %>
  </p>
  <p>
    For educational purposes only.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Flix', root_path %></h1>
    <nav>
      <p>
      <% if current_user %>
        <%= link_to current_user.name, current_user %>
        <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>
        <% else %>
        <%= link_to "Sign Up", signup_path, class: 'button' %>
        <%= link_to "Sign In", new_session_path, class: 'button' %>
        <% end %>
      </p>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-movies">
        <%= link_to 'All Movies', movies_path, class: 'button' %>
      </li>
      <% if current_user_admin? %>
      <li class="create-movie">
        <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
      </li>
      <% end %>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super-Heroic Flix</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render "layouts/header" %>

    <div id="wrapper">

      <% if flash[:notice] %>
        <p class= "flash notice">
          <%= flash[:notice] %>
        </p>
      <% end %>

      <% if flash[:alert] %>
        <p class="flash alert">
         <%= flash[:alert] %>
        </p>
      <% end %>

      <div id="container">
        <section id="sidebar">
          <%= render "layouts/sidebar" %>
        </section>
        <section id="content">
          <%= yield %>
        </section>
      </div>

    </div>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.humanize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>